package: mblock
version: '1.5.1'
name: MBlock
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/mblock

page:
    title: 'translate:title'
    pjax: true
    perm: mblock[]
    icon: rex-icon fa-train
    subpages:
        overview: { title: 'translate:overview' }
        demo:
            title: 'translate:demo_base'
            subpages:
                demo_mform: { title: 'translate:demo_mform' }
                demo_html: { title: 'translate:demo_html' }

requires:
    redaxo: '^5.1.0'
