package: mblock
version: 4.0.0-dev
name: MBlock
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/mblock

page:
    title: translate:title
    pjax: true
    perm: mblock[]
    icon: rex-icon fa-train
    subpages:
        overview: { title: translate:overview }
        demo:
            title: translate:demo_base
            subpages:
                demo_mform: { title: translate:demo_mform }
                demo_html: { title: translate:demo_html }
        rexform_demo: { title: translate:rexform_demo }
        help: { title: translate:help, subPath: README.md }

requires:
    redaxo: ^5.12.0
    php:
        version: ^8.1
        extensions: [xml]
