package: mblock
version: 4.0.0-beta2
name: MBlock
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/mblock

page:
    title: translate:title
    pjax: true
    perm: mblock[]
    icon: rex-icon fa-train
    subpages:
        overview: { title: 'MBlock 4.0' }
        demo:
            title: translate:demo_base
            subpages:
                demo_mform: { title: translate:demo_mform }
                demo_html: { title: translate:demo_html }
        best_practices: { title: 'Best Practices' }
        api: { title: 'API', subPath: API.md }
        help: { title: 'translate:help', subPath: README.md }
        settings: { title: translate:configuration, itemClass: 'pull-right' }

requires:
    redaxo: ^5.18.0
    packages:
        bloecks: '^5.2.0'

           
