package: mblock
version: 4.3.3
name: MBlock
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/mblock

page:
    title: translate:title
    pjax: true
    perm: mblock[]
    icon: rex-icon fa-layer-group
    subpages:
        overview: { title: 'MBlock', icon: 'rex-icon fa-layer-group' }
        demo:
            title: translate:demo_base
            subpages:
                demo_mform: { title: translate:demo_mform }
                demo_html: { title: translate:demo_html }
        best_practices: { title: 'translate:mblock_best_practices' }
        changelog: { title: 'translate:mblock_changelog', subPath: CHANGELOG.md, icon: 'rex-icon fa-history' }
        api: { title: 'API', subPath: API.md, itemClass: 'pull-right', icon: 'rex-icon fa-code' }
        help: { title: 'translate:help', subPath: README.md, itemClass: 'pull-right', icon: 'rex-icon fa-question-circle' }
        settings: { title: translate:configuration, itemClass: 'pull-right', icon: 'rex-icon fa-cog' }

requires:
    redaxo: ^5.18.0

suggests:
    packages:
        mform: ^6.0

# Default addon configuration
default_config:
    mblock_theme: 'standard'
    mblock_copy_paste: true
    mblock_online_offline: true
    mblock_scroll: true
    mblock_delete_confirm: true
