name: Publish release

on:
  release:
    types:
      - published

jobs:
  redaxo_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: FriendsOfREDAXO/installer-action@1.0.0
      with:
        myredaxo-username: ${{ secrets.MYREDAXO_USERNAME }}
        myredaxo-api-key: ${{ secrets.MYREDAXO_API_KEY }}
        description: ${{ github.event.release.body }}
